### ISSUE TITLE
Add ServiceErrorHandler for authenticated services

### ISSUE THREAD

**Issue by jarreds** [jmcardon/tsec#108]
Http4s has a `ServiceErrorHandler` that you can intercept errors with. That error handler is not invoked when using authenticated services.

**Comment by jmcardon** [comment]
We spoke about this on gitter, but I'm half-considering closing this issue.

Your `TsecAuthService` is just a `SecuredRequest => F[Response[F]]` (in the shape of `Kleisli[OptionT[F,?], SecuredRequest[F, I, A], Response[F]]`) which you can use cats to `handleError`/With. Adding this as part of the library as a convenience method seems... not worth it in a sense? 

I mean in theory, that block should _never_ be hit. unless something really unexpected goes wrong.

**Comment by jarreds** [comment]
👍 to closing
