### ISSUE TITLE
Json decoding of JWTClaims fails when field "aud" is present

### ISSUE THREAD

**Issue by jfraudeau** [jmcardon/tsec#122]
circe decoding that fails on
`aud <- c.downField(Audience).as[Option[Either[String, List[String]]]]`
 as the default decoder for Either expects a jsonObject with fields "Left" or "Right".
A workaround would be to use a custom decoder like mentionned in circe/circe#751

**Comment by jmcardon** [comment]
Thank you, I'll put out a fix.

**Comment by jmcardon** [comment]
Closed by #123
