### ISSUE TITLE
Add the ability to resolve JW algorithms / signatures dynamically.  

### ISSUE THREAD

**Issue by Baccata** [jmcardon/tsec#165]
Provided a `String` (and maybe a crypto backend) , I would like to be able to find the associated `JWA` instance (and its associated `SignatureAPI` or `MacAPI), so that I can get my keys from external sources.

**Comment by jmcardon** [comment]
So, I could do this if I stuck to an enumerable subset of instances and/or standardized strings and returned a `JWT[Any]` or whatever.

That said, it feels like cheating the type system to do this and I don't see why I would want to support that use case. I think Jose4j is a much better fit for this kind of work than tsec, _and_ it supports JWE

**Comment by Baccata** [comment]
Fair enough. Thanks for the reply 😄
