### ISSUE TITLE
NativePRNGNonBlocking in ManagedRandom

### ISSUE THREAD

**Issue by Gesnuby** [jmcardon/tsec#177]
Running examples for password hashing on Windows causes `java.security.NoSuchAlgorithmException: NativePRNGNonBlocking SecureRandom not available` exception. `NativePRNGNonBlocking` algorithm for SecureRandom doesn't exist on Windows OS.

**Comment by rsoeldner** [comment]
True, Thank you https://docs.oracle.com/javase/8/docs/technotes/guides/security/SunProviders.html

**Comment by jmcardon** [comment]
Tsec does not make an effort to support windows OS. 

Maybe I should make this clearer, but I'm not planning on changing anything in the codebase to support windows

**Comment by rodrigopalhares** [comment]
The hardcoded algorithm is not a good architecture decision. Anyway, you have 3 workaround options:

Option 1: Use another library

Option 2: Fork and change the `ManagedRandom` to something like this [Try catch workaround](https://github.com/kawasima/bouncr/commit/18c106ff0d5e0c9c3c9cf8466f17734796506f32)

Option 3: If you not using windows in production and you want your dev to have freedom of choice. You can run this on application start. *Do not use this in production, you may have some side effect.*

```
  private def tsecWindowsFix(): Unit =
    try {
      SecureRandom.getInstance("NativePRNGNonBlocking")
      ()
    } catch {
      case _: NoSuchAlgorithmException =>
        val secureRandom = new SecureRandom()
        secureRandom.getProvider.put("SecureRandom.NativePRNGNonBlocking", "sun.security.provider.SecureRandom")
        secureRandom.getProvider.get(s"SecureRandom.${secureRandom.getAlgorithm}")
        Security.addProvider(secureRandom.getProvider)
        ()
    }
```

**Comment by joshuakfarrar** [comment]
I have a Windows-based dev machine I sometimes hack on and @rodrigopalhares' solution worked for me.
