### ISSUE TITLE
The hardcoded use of NativePRNGNonBlocking in ManagedRandom causes problems on Windows

### ISSUE THREAD

**Issue by lancewalton** [jmcardon/tsec#183]
Due to unfortunate reasons, one member of the team I'm working with has to use Windows.

In our code, we call tsec.cipher.symmetric.jca.GCM.randomIVStrategy. This ends up calling tsec.common.ManagedRandom.init which has a var 'cachedRand', which calls SecureRandom with "NativePRNGNonBlocking".

Unfortunately, NativePRNGNonBlocking is not necessarily available on Windows, & we have to use SHA1PRNG instead, but we can't pass that to tsec.common.ManagedRandom.

I'm not sure if there is a different way to get an IvGen instance other than by calling tsec.cipher.symmetric.jca.GCM.randomIVStrategy.

Can you help?

**Comment by rsoeldner** [comment]
Hey @lancewalton ,

Windows is not supported, check #178  and #177 
Best would be to switch to a normal OS :+1:

**Comment by rhyskeepence** [comment]
I'm bumping into this issue as well. I fully support your "switch to a normal OS" philosophy however my current client is a huge bureaucratic investment bank and switching operating system is not an option.

Would you be open to a pull request to make SecureRandomIdGenerator a typeclass? I'd rather not fork the project or monkey patch.

It would also allow the use of DRBG on Java 9 which would benefit everyone.

**Comment by ChristopherDavenport** [comment]
Would you like me to set up some Windows CI on the project?

**Comment by jmcardon** [comment]
@ChristopherDavenport If you'd like. I'm reopening this with the advent of #187

**Comment by jmcardon** [comment]
Alright, I'm closing this. There seems to be no desire to take ownership of windows code, despite benefiting absolutely none of the contributors to this project.

**Comment by rodrigopalhares** [comment]
The hardcoded algorithm is not a good architecture decision. Anyway, you have 3 workaround options:

Option 1: Use another library

Option 2: Fork and change the `ManagedRandom` to something like this [Try catch workaround](https://github.com/kawasima/bouncr/commit/18c106ff0d5e0c9c3c9cf8466f17734796506f32)

Option 3: If you not using windows in production and you want your dev to have freedom of choice. You can run this on application start. *Do not use this in production, you may have some side effect.*

```
  private def tsecWindowsFix(): Unit =
    try {
      SecureRandom.getInstance("NativePRNGNonBlocking")
      ()
    } catch {
      case _: NoSuchAlgorithmException =>
        val secureRandom = new SecureRandom()
        secureRandom.getProvider.put("SecureRandom.NativePRNGNonBlocking", "sun.security.provider.SecureRandom")
        secureRandom.getProvider.get(s"SecureRandom.${secureRandom.getAlgorithm}")
        Security.addProvider(secureRandom.getProvider)
        ()
    }
```

**Comment by ScalaWilliam** [comment]
> I'm bumping into this issue as well. I fully support your "switch to a normal OS" philosophy however my current client is a huge bureaucratic investment bank and switching operating system is not an option.
> 
> Would you be open to a pull request to make SecureRandomIdGenerator a typeclass? I'd rather not fork the project or monkey patch.
> 
> It would also allow the use of DRBG on Java 9 which would benefit everyone.

Running into this issue too!
