### ISSUE TITLE
Release forgotten dependency tsec-bouncy v0.0.1-RC1

### ISSUE THREAD

**Issue by dborisenko** [jmcardon/tsec#195]
I was trying to export `tsec-http4s` of version `0.0.1-RC1` and I got the following error:
`sbt.librarymanagement.ResolveException: unresolved dependency: io.github.jmcardon#tsec-bouncy_2.12;0.0.1-RC1: not found`.

I checked maven central and found that one of the transitive dependencies `tsec-http4s` of version `0.0.1-RC1` wasn't released there: http://mvnrepository.com/artifact/io.github.jmcardon/tsec-bouncy

**Comment by jmcardon** [comment]
Fixed: https://search.maven.org/artifact/io.github.jmcardon/tsec-bouncy_2.11/0.0.1-RC1/jar

Apologies, I don't have the release process automated and that package isn't part of the default release dependencies.

**Comment by jmcardon** [comment]
Also ping @aeons since you wanted this
