### ISSUE TITLE
tsec-http4s project is not being built

### ISSUE THREAD

**Issue by DylanArnold** [jmcardon/tsec#379]
I checked out version `0.4.0-M1` and realised that `tsec-http4s` is not being compiled. If you check out `build.sbt` the project is commented out. 

What is the status of `tsec-http4s`? If it's being removed it should be removed from `README.md`. The project is also referenced from the http4s documentation which should be updated.

If it's still being maintained I'm just bringing this to attention. If you need someone to try and get the project to compile I could possibly look at creating a pull request.

**Comment by Lactem** [comment]
I was curious about this as well. It looks like [this branch](https://github.com/jmcardon/tsec/tree/tsec-http4s-fixes) was trying to update tsec-http4s but ran into test failures in Travis. Were the fixes for these tests non-trivial?

**Comment by ScalaWilliam** [comment]
It looks it's not even compiling.

**Comment by ScalaWilliam** [comment]
PR #387

@DylanArnold @Lactem please help get @ChristopherDavenport's attention on this :-)

**Comment by DylanArnold** [comment]
@ScalaWilliam Fantastic stuff! :heart:

**Comment by Lactem** [comment]
> PR #387
> 
> @DylanArnold @Lactem please help get @ChristopherDavenport's attention on this :-)

Will comment on the PR, too -- thanks for doing this!
