### ISSUE TITLE
Adding custom claims to JWTAuthenticator?

### ISSUE THREAD

**Issue by parsnips** [jmcardon/tsec#76]
First, thanks for building this library. 

I'm using a `JWTAuthenticator` and it works great.  I want to add custom claims object to pass some information client side.  Since `AuthenticatorService.create` is implementation agnostic the best option I can think of is to make some sort of method which constructs JWT's a la https://jmcardon.github.io/tsec/docs/jwt-mac.html and avoid using `JWTAuthenticator.create`.  Is this your take as well? 

The docs could use a blurb on this, you open to contributors?

**Comment by jmcardon** [comment]
Hi, thanks for opening an issue! Yes, we welcome any and all contributors to this project.

Re: custom claims, I believe could be related to #59 (I think that issue means claims and not headers).

As far as this issue: this is open to discussion. Passing information inside an authentication token raises a flag in my head. I mean, tokens are sent along with every request, so sending arbitrary info in the claims will increase the network load and make token creation/verification slower based upon how much data you want to put in there.

In tsec, the philosophy tends to be along the lines of "prevent people from shooting themselves in the foot". This opens users up to doing something they really shouldn't be doing unless they have a good reason to.

So I'm lukewarm on this. I'd like to hear your reasoning behind it (i.e maybe you're doing your own verification of the JWT on the client). If it's something that is a common enough, then I'll incline to agree. Alternatively, you can open a PR anyway and we can review the use case :+1: 

Pinging @hrhino for a second opinion here.

**Comment by jmcardon** [comment]
oh and re: the docs, there I 100% agree, maybe we could be more informative that we're a tad opinionated on how we create tokens.

**Comment by parsnips** [comment]
The use case I'm wanting to support is to include encoding role information into the jwt, and create authorization middleware that can get role information from a jwt.  As far as I understand, use cases like this are the raison d'etre for custom claims.

**Comment by jmcardon** [comment]
Is there any particular reason you cannot get the role information from the user object in the backing store? Authorization in tsec is appled after authentication, so you don't need to extract it from the jwt at all if your authorization info is attached to your user model. It would be redundant information (unless you want to have the user role information authenticated). 

All authenticators currently have to go through a user store. This is the main thing that makes it redundant. I do think custom claims in the JWT need to be added, but I'm unsure whether this is common enough use case to be a standard. 

That said I'm open to a PR to see what you have in mind. Im unsure how to alter the abstraction for your use case currently.

**Comment by parsnips** [comment]
>Is there any particular reason you cannot get the role information from the user object in the backing store? Authorization in tsec is appled after authentication, so you don't need to extract it from the jwt at all if your authorization info is attached to your user model. It would be redundant information (unless you want to have the user role information authenticated).

That's a fair point.  For my use case the JWT already contains the state I care about: the `sub` claim and potentially a `role`-like claim.  The service consuming the jwt doesnt have access to the real user store. In some ways `JWTAuthenticator.stateless` is a  bit misleading since it does require an impl of `BackingStore.get`.

Feel free to close this!

**Comment by jmcardon** [comment]
Oh I guess. Feel free to submit a docs change if you feel it is appropriate.

In a sense, what i meant to say is the _token itself_ is stateless. Stateful token would imply the token itself has a backingstore, not just the user.

If you want custom behavior, in a sense, the only way to extract the user would be by encoding the information into the claim itself. Im not against adding a purely stateless implementation at all.

What do you think? I'm for it, but it seems like more of a custom use case
