### ISSUE TITLE
[tsec-http4s] Allow customizing what happens on auth failure

### ISSUE THREAD

**Issue by aeons** [jmcardon/tsec#78]
Currently an auth failure results in a 401 response. It can sometimes be useful to instead redirect to some form of login page. This is not possible out of the box, but can be achieved by mapping over the result.

A customization option to allow for changing the failure case would be nice to have.

Maybe something like
```scala
// in SecuredRequestHandler
def liftService(service: TSecAuthService[F, User, Auth], fallback: => Response[F]): HttpService[F] =
  defaultMiddleware(service).handleError(_ => fallback))
```

**Comment by jmcardon** [comment]
Re: on gitter, :+1: to a PR for this.

**Comment by aeons** [comment]
I had a quick stab at this, but then I got distracted and never got back to it. Sorry :)
