### ISSUE TITLE
Howto Compose Authorized Services

### ISSUE THREAD

**Issue by parsnips** [jmcardon/tsec#81]
Let's say I'm using an RBAC and i have several roles:

`Role.user`, `Role.customer`, `Role.vendor`

And I'm using an `SecuredRequestHandler` , I want to do something like like

```
handler.authorized(Role.user, Role.customer) { } <+> // can access
handler.authorized(Role.customer, Role.vendor) { } <+> // 404
handler { } // 404
```

requests to the right of the first authorized will 404 due to: https://github.com/http4s/http4s/pull/1530

Is there a way to compose routes that require different authorization?

**Comment by rsoeldner** [comment]
There is an `authorization` monoid see https://jmcardon.github.io/tsec/docs/http4s/authorization.html .

Can you post a complete example, I can try to help here :+1:

**Comment by parsnips** [comment]
Let me know if you need something fully compilable:

```
val authenticator: StatelessJWTAuthenticator[Eff[S, ?], UUID, User, HMACSHA256] =
  JWTAuthenticator.stateless(
    expiry = 1.hours,
    maxIdle = None,
    identityStore = new SomeBackingStore[S](),
    signingKey = signingKey)

val secured: SecuredRequestHandler[Eff[S, ?], UUID, User, AugmentedJWT[HMACSHA256, UUID]] =
  SecuredRequestHandler(authenticator)

val vendorOnly = BasicRBAC[Eff[S, ?], Role, User, AugmentedJWT[HMACSHA256, UUID]](Role.Vendor)
val customerOrVendor = BasicRBAC[Eff[S,?], Role, User, AugmentedJWT[HMACSHA256, UUID]](Role.Vendor, Role.Customer)

val api: HttpService[Eff[S, ?]] = {
  secured.authorized(vendorOnly) {
    {
      case GET -> Root / "path1" asAuthed user =>
        for {
          response <- Ok(user.asJson)
        } yield response
    }
  } <+>
  secured.authorized(customerOrVendor) {
    {
      case GET -> Root / "path2" asAuthed user =>
        for {
          response <- Ok(user.asJson)
        } yield response
    }
  }
}
```

**Comment by parsnips** [comment]
https://github.com/parsnips/tsec/commit/02fe55ae154669719624bde827e63e9836b21397

**Comment by parsnips** [comment]
Added a [test case](https://github.com/jmcardon/tsec/commit/26047a0acf96e60c75e7094acf62b15662a5fd76) demonstrating the issue showing you cannot use role base auth for different verb on same resource.

It was pointed out in gitter that you could use a router.. but at that point roles begin polluting the url structure. Given a non-trivial amount of roles, combination explosion becomes a serious problem for someone using this library.

**Comment by jmcardon** [comment]
@parsnips Thank you for pointing out the issues.

Documenting for the sake of this issue, on [gitter](https://gitter.im/http4s/http4s?at=5a3da84a0163b028106c9b02), there was a discussion about this.

So currently, there _is_ a way of composing these, but it's quite manual. I do agree we need more helpers here.
