### ISSUE TITLE
TSecAuthService composition via SemigroupK

### ISSUE THREAD

**Issue by jarreds** [jmcardon/tsec#88]
We should be able to:

```scala
val serviceOne: TSecAuthService[IO, DummyUser, Authenticator[Int]] = ???
val serviceTwo: TSecAuthService[IO, DummyUser, Authenticator[Int]] = ???
serviceOne <+> serviceTwo
```

Currently, this results in a compiler error. I believe we have an issue similar to https://github.com/http4s/http4s/pull/1509

**Comment by jmcardon** [comment]
I agree. Would you like to submit a PR? I am a bit gated in how much I can work from China until I am back home.
